services:
  task-service-db:
    build:
      context: db/task-management-service
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task-service-db
    container_name: postgresql

